// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	elastic "github.com/datadog/threatest/pkg/threatest/matchers/elastic"

	mock "github.com/stretchr/testify/mock"
)

// ElasticSecurityDetectionAlertsAPI is an autogenerated mock type for the ElasticSecurityDetectionAlertsAPI type
type ElasticSecurityDetectionAlertsAPI struct {
	mock.Mock
}

// CloseAlert provides a mock function with given fields: ctx, id
func (_m *ElasticSecurityDetectionAlertsAPI) CloseAlert(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CloseAlert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchAlerts provides a mock function with given fields: ctx, query
func (_m *ElasticSecurityDetectionAlertsAPI) SearchAlerts(ctx context.Context, query string) ([]elastic.ElasticSecurityDetectionAlert, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchAlerts")
	}

	var r0 []elastic.ElasticSecurityDetectionAlert
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]elastic.ElasticSecurityDetectionAlert, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []elastic.ElasticSecurityDetectionAlert); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]elastic.ElasticSecurityDetectionAlert)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewElasticSecurityDetectionAlertsAPI creates a new instance of ElasticSecurityDetectionAlertsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticSecurityDetectionAlertsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticSecurityDetectionAlertsAPI {
	mock := &ElasticSecurityDetectionAlertsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
