// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// SplunkAPI is an autogenerated mock type for the SplunkAPI type
type SplunkAPI struct {
	mock.Mock
}

// CloseNotable provides a mock function with given fields: id
func (_m *SplunkAPI) CloseNotable(id string) error {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for CloseNotable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchNotables provides a mock function with given fields: filter
func (_m *SplunkAPI) SearchNotables(filter map[string]string) ([]map[string]interface{}, error) {
	ret := _m.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for SearchNotables")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]string) ([]map[string]interface{}, error)); ok {
		return rf(filter)
	}
	if rf, ok := ret.Get(0).(func(map[string]string) []map[string]interface{}); ok {
		r0 = rf(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSplunkAPI creates a new instance of SplunkAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSplunkAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SplunkAPI {
	mock := &SplunkAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
