// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	matchers "github.com/datadog/threatest/pkg/threatest/matchers"
	mock "github.com/stretchr/testify/mock"
)

// EventsAPI is an autogenerated mock type for the EventsAPI type
type EventsAPI struct {
	mock.Mock
}

// SearchEvents provides a mock function with given fields: ctx, query, opts
func (_m *EventsAPI) SearchEvents(ctx context.Context, query string, opts ...matchers.SearchOption) ([]map[string]interface{}, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SearchEvents")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) ([]map[string]interface{}, error)); ok {
		return rf(ctx, query, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) []map[string]interface{}); ok {
		r0 = rf(ctx, query, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...matchers.SearchOption) error); ok {
		r1 = rf(ctx, query, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewEventsAPI creates a new instance of EventsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventsAPI {
	mock := &EventsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
