before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.BuildVersion={{.Version}}

    dir: cmd/threatest
    binary: threatest
brews:
  - name: threatest
    tap:
      owner: datadog
      name: threatest
    folder: Formula
    url_template: "https://github.com/DataDog/threatest/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    license: Apache-2.0
    homepage: "https://github.com/DataDog/threatest"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'