// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	datadogV2 "github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"

	mock "github.com/stretchr/testify/mock"
)

// DatadogSecuritySignalsAPI is an autogenerated mock type for the DatadogSecuritySignalsAPI type
type DatadogSecuritySignalsAPI struct {
	mock.Mock
}

// CloseSignal provides a mock function with given fields: ctx, id
func (_m *DatadogSecuritySignalsAPI) CloseSignal(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CloseSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchSignals provides a mock function with given fields: ctx, query
func (_m *DatadogSecuritySignalsAPI) SearchSignals(ctx context.Context, query string) ([]datadogV2.SecurityMonitoringSignal, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchSignals")
	}

	var r0 []datadogV2.SecurityMonitoringSignal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]datadogV2.SecurityMonitoringSignal, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []datadogV2.SecurityMonitoringSignal); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV2.SecurityMonitoringSignal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDatadogSecuritySignalsAPI creates a new instance of DatadogSecuritySignalsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDatadogSecuritySignalsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *DatadogSecuritySignalsAPI {
	mock := &DatadogSecuritySignalsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
