package atomic

// The following structures were designed following the Atomic test specification:
// https://github.com/redcanaryco/atomic-red-team/blob/master/atomic_red_team/spec.yaml

type Technique struct {
	AttackTechnique string `yaml:"attack_technique"`
	DisplayName     string `yaml:"display_name"`
	AtomicTests     []Test `yaml:"atomic_tests"`
}

type Test struct {
	Name                   string                   `yaml:"name"`
	AutoGeneratedGUID      string                   `yaml:"auto_generated_guid"`
	Description            string                   `yaml:"description"`
	SupportedPlatforms     []string                 `yaml:"supported_platforms"`
	InputArguments         map[string]InputArgument `yaml:"input_arguments,omitempty"`
	DependencyExecutorName *string                  `yaml:"dependency_executor_name,omitempty"`
	Dependencies           []Dependency             `yaml:"dependencies,omitempty"`
	Executor               Executor                 `yaml:"executor"`
}

type InputArgument struct {
	Description string  `yaml:"description"`
	Type        string  `yaml:"type"`
	Default     *string `yaml:"default,omitempty"`
}

type Dependency struct {
	Description      string `yaml:"description"`
	PreReqCommand    string `yaml:"prereq_command"`
	GetPreReqCommand string `yaml:"get_prereq_command"`
}

type Executor struct {
	Name              string  `yaml:"name"`
	ElevationRequired *bool   `yaml:"elevation_required,omitempty"`
	Command           *string `yaml:"command,omitempty"`
	CleanupCommand    *string `yaml:"cleanup_command,omitempty"`
	Steps             *string `yaml:"steps,omitempty"`
}
