# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Threatest < Formula
  desc ""
  homepage "https://github.com/DataDog/threatest"
  version "1.2.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/threatest/releases/download/v1.2.3/threatest_Darwin_arm64.tar.gz"
      sha256 "da73302d9ec39ef39cea8ac1ad695309cfade47ca7f47b5f171b2bad53d59eb6"

      def install
        bin.install "threatest"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/threatest/releases/download/v1.2.3/threatest_Darwin_x86_64.tar.gz"
      sha256 "9e728515e9fc9d74c2720ef08bb62ca364ff23b4f4d698c1a4b08933746a3717"

      def install
        bin.install "threatest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/threatest/releases/download/v1.2.3/threatest_Linux_x86_64.tar.gz"
      sha256 "17d848c912f11363be093dda822aacc4e3c9bf01cdcf2996796dcec12a2b4b34"

      def install
        bin.install "threatest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/threatest/releases/download/v1.2.3/threatest_Linux_arm64.tar.gz"
      sha256 "ecdcddb82b35a4e641a7eca9fbf987facc0d2ce9231cc017d368ee1ffbfdb06c"

      def install
        bin.install "threatest"
      end
    end
  end
end
