// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	datadogV2 "github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"

	matchers "github.com/datadog/threatest/pkg/threatest/matchers"

	mock "github.com/stretchr/testify/mock"
)

// LogsAPI is an autogenerated mock type for the LogsAPI type
type LogsAPI struct {
	mock.Mock
}

// SearchLogs provides a mock function with given fields: ctx, query, opts
func (_m *LogsAPI) SearchLogs(ctx context.Context, query string, opts ...matchers.SearchOption) ([]datadogV2.Log, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SearchLogs")
	}

	var r0 []datadogV2.Log
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) ([]datadogV2.Log, error)); ok {
		return rf(ctx, query, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) []datadogV2.Log); ok {
		r0 = rf(ctx, query, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV2.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...matchers.SearchOption) error); ok {
		r1 = rf(ctx, query, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogsAPI creates a new instance of LogsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogsAPI {
	mock := &LogsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
