// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	datadogV2 "github.com/DataDog/datadog-api-client-go/v2/api/datadogV2"
	matchers "github.com/datadog/threatest/pkg/threatest/matchers"

	mock "github.com/stretchr/testify/mock"
)

// SignalsAPI is an autogenerated mock type for the SignalsAPI type
type SignalsAPI struct {
	mock.Mock
}

// CloseSignal provides a mock function with given fields: ctx, id
func (_m *SignalsAPI) CloseSignal(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for CloseSignal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SearchSignals provides a mock function with given fields: ctx, query, opts
func (_m *SignalsAPI) SearchSignals(ctx context.Context, query string, opts ...matchers.SearchOption) ([]datadogV2.SecurityMonitoringSignal, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for SearchSignals")
	}

	var r0 []datadogV2.SecurityMonitoringSignal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) ([]datadogV2.SecurityMonitoringSignal, error)); ok {
		return rf(ctx, query, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) []datadogV2.SecurityMonitoringSignal); ok {
		r0 = rf(ctx, query, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]datadogV2.SecurityMonitoringSignal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...matchers.SearchOption) error); ok {
		r1 = rf(ctx, query, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSignalsAPI creates a new instance of SignalsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSignalsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SignalsAPI {
	mock := &SignalsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
