// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	matchers "github.com/datadog/threatest/pkg/threatest/matchers"
	mock "github.com/stretchr/testify/mock"
)

// TelemetryMatcher is an autogenerated mock type for the TelemetryMatcher type
type TelemetryMatcher struct {
	mock.Mock
}

// Cleanup provides a mock function with given fields: ctx, uuid
func (_m *TelemetryMatcher) Cleanup(ctx context.Context, uuid string) error {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HasExpected provides a mock function with given fields: ctx, uuid
func (_m *TelemetryMatcher) HasExpected(ctx context.Context, uuid string) (bool, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for HasExpected")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Related provides a mock function with given fields: ctx, uuid
func (_m *TelemetryMatcher) Related(ctx context.Context, uuid string) (map[string]matchers.ThreatestEvent, error) {
	ret := _m.Called(ctx, uuid)

	if len(ret) == 0 {
		panic("no return value specified for Related")
	}

	var r0 map[string]matchers.ThreatestEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]matchers.ThreatestEvent, error)); ok {
		return rf(ctx, uuid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]matchers.ThreatestEvent); ok {
		r0 = rf(ctx, uuid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]matchers.ThreatestEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, uuid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, query, opts
func (_m *TelemetryMatcher) Search(ctx context.Context, query string, opts ...matchers.SearchOption) (map[string]matchers.ThreatestEvent, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 map[string]matchers.ThreatestEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) (map[string]matchers.ThreatestEvent, error)); ok {
		return rf(ctx, query, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...matchers.SearchOption) map[string]matchers.ThreatestEvent); ok {
		r0 = rf(ctx, query, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]matchers.ThreatestEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...matchers.SearchOption) error); ok {
		r1 = rf(ctx, query, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// String provides a mock function with no fields
func (_m *TelemetryMatcher) String() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for String")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewTelemetryMatcher creates a new instance of TelemetryMatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTelemetryMatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TelemetryMatcher {
	mock := &TelemetryMatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
